name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Maleesha29  # Replace with your username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push the generated snake animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Maleesha29/Maleesha29.git main
